### PR TITLE
Load SID and STAR procedures from MSFS

### PR DESCRIPTION
**Pull request by icykoneko**
I think I've got it working :)  It's not combining parallel runways (not sure if that's a problem or more an annoyance).  I'm not really happy with how I had to manage the table row ids, as I wasn't able to reuse the existing approach and transition record classes.  It felt like they'd turn into very ugly code, very fast if I did.

### CODE REVIEW

**Comment by icykoneko** [comment]
Oh yea, it works!
lnm-msfs-sid-star-screenshot
msfs-loaded-sid-star-from-lnm-screenshot

**Comment by icykoneko** [comment]
Something I noticed, and I don't know if I can really do anything about it...
Look at MSLP, SID 07, TUKORE.  Reading the BGL directly produces a similar route, but the `RF` leg is not smooth like it is in the navigraph dataset.  The BGL has nothing in the "recommended fix", so I didn't set it to anything, but it looks like that may need to be fixed up?  I'm sure the departure still works in the game itself (or maybe not hahaha), but it's kinda meh.

**Comment by icykoneko** [comment]
how_to_automatically_fill_in_recommended_rf_leg_fixes

The only other data for `RF` legs is the distance along track.  There's nothing to tell you how far away the center-point of the arc is from either waypoint. I figure it's safe to assume the distance from that point should be the same at both fixes and tried to plot it out.  Other than removing the warning popup, I don't think it'd impact the flight plan given to the game.

**Comment by albar965** [comment]
**Terrific! Billion thanks!**

About the RF: It seems that the recommended fix is missing for most of these legs which makes them unusable. Same for approachhes. :frowning_face: One of us should submit a ticket on MSFS Zendesk. I can take care of this.

**Pull request merged**
